# Algorithm Explanation:
# Problem: Given two strings s and t, where t is generated by shuffling s and adding one extra character, find the extra character.
# Approach:
# 1. Count the frequency of each character in both strings using Counter.
# 2. Iterate through each character in t:
#    - If the character is not in s, return it (it's the extra character).
#    - If the count of the character in t is greater than in s, return it (it's the extra character).
# 3. Print the result.

from collections import Counter
def find_the_difference(s, t):
    counter_s, counter_t = Counter(s), Counter(t)
    
    for c in counter_t:
        if c not in counter_s:
            return c
        if counter_s[c] < counter_t[c]:
            return c
    
s="avcd"
t="avcde"
print(find_the_difference(s,t))