# Algorithm Explanation:
# Problem: Given two strings s and t, where t is generated by shuffling s and adding one extra character, find the extra character.
# Approach:
# 1. Sort both strings to align their characters in order.
# 2. Use two pointers to compare characters at each position.
#    - If characters at the same position are equal, move to the next position.
#    - If a mismatch is found, return the character from t at that position (it's the extra character).
# 3. If all characters match, the extra character is at the end of t; return it.

def find_the_difference(s, t):
    sorted_s = sorted(s)
    sorted_t = sorted(t)
    i=0
    j=len(sorted_s)-1
    while i<=j:
        if sorted_t[i] == sorted_s[i]:
            i+=1
        elif sorted_t[i] != sorted_s[i]:
            return sorted_t[i]
    return sorted_t[i]
s="avcd"
t="avcde"
print(find_the_difference(s,t))